name: Bug Report
description: Create a report to help fix issues.
labels: ["Type: Bug", "Status: Triage"]
body:
- type: markdown
  attributes:
    value: |
      ✋ This form is for bugs reports ONLY.

      For:
      - Questions,
      - Help,
      - Ideas,
      - Feature requests,
      - Youre Not sure,
      - Yuore Not techinically inclined
      
      => PLEASE use the [Discussion](https://github.com/victornpb/undiscord/discussions) tab instead.
      
      ALSO:
      
      Before filing, please check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment. 
      
- type: input
  attributes:
    label: Undiscord Version
    description: You can see the version in the bottom right corner or in the ViolentMonkey or TamperMonkey settings.
    placeholder: v0.0.0
  validations:
    required: true
- type: input
  attributes:
    label: Browser
    description: What browser you re using undiscord. Go to chrome://version/ and copy the version
    placeholder: 110.0.5481.177 (Official Build) (x86_64)
  validations:
    required: true
- type: input
  attributes:
    label: Extension
    description: Which extension are you using
    placeholder: ViolentMonkey / TamperMonkey / Other method
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: Tell us what you did!
    placeholder: |
      1. Something you did
      2. Something you did next
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual results
    description: What happens after the above steps have been followed.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected results
    description: What should happen after the above steps have been followed.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Bug affects
    options:
      - label: DMs
      - label: DMs (group)
      - label: Channels
      - label: Channel (NSFW)
      - label: 
- type: textarea
  attributes:
    label: Additional information & file uploads  
    description: |
      You can add screenshots and additional information that is relevant to the issue in the comments below.
      IMPORTANT: Make sure to verify you're not sharing any personal information. Redact any ID's or Names that might appear.
      Github Issues are publicly visible, do not post sensitive information here!
  validations:
    required: true
